/*
  This class has been generated by the Code Generator
*/

package com.chubb.pfp.pfpwsappserverpackage;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;


public class caseAlignmentMatrixPFP extends caseAlignmentMatrixPFPBase
{
    public caseAlignmentMatrixPFP()
    {
        this((BusObjectConfig)null);
    }

    public caseAlignmentMatrixPFP(BusObjectConfig config)
    {
        super(config);
    }

    public static BusObjectIterator<com.chubb.pfp.pfpwsappserverpackage.caseAlignmentMatrixPFP> GetDepartmentsfromCaseMatrixPFP(String RequestType)
    {
        String queryText = "select DISTINCT ReceivingDepartment  from caseAlignmentMatrixPFP where RequestType =:RequestType ";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("RequestType", "caseAlignmentMatrixPFP.RequestType", QueryObject.PARAM_STRING, RequestType);        
        query.setResultClass(caseAlignmentMatrixPFP.class);
        return query.getObjects();
    }
	public static BusObjectIterator<com.chubb.pfp.pfpwsappserverpackage.caseAlignmentMatrixPFP> getActivityTypebyDepFromCaseMatrixPFP(String RequestType, String Department)
    {
         String queryText = "select DISTINCT ActivityType  from caseAlignmentMatrixPFP where RequestType =:RequestType and ReceivingDepartment  = :Department";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("RequestType", "caseAlignmentMatrixPFP.RequestType", QueryObject.PARAM_STRING, RequestType);
        query.addParameter("Department", "caseAlignmentMatrixPFP.ReceivingDepartment", QueryObject.PARAM_STRING, Department);        		
        query.setResultClass(caseAlignmentMatrixPFP.class);
        return query.getObjects();
    }

 public static BusObjectIterator<com.chubb.pfp.pfpwsappserverpackage.caseAlignmentMatrixPFP> GetAllDistinctActivityTypes()
    {
        String queryText = "select DISTINCT ActivityType from caseAlignmentMatrixPFP where ActivityType NOT IN ('Other/General Inquiry') ";
        QueryObject query = new QueryObject(queryText);             
        query.setResultClass(caseAlignmentMatrixPFP.class);
        return query.getObjects();
    }

}
