/*
  This class has been generated by the Code Generator
*/

package com.chubb.pfp.pfpwsappserverpackage;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;


public class dropdown_table extends dropdown_tableBase
{
    public dropdown_table()
    {
        this((BusObjectConfig)null);
    }

    public dropdown_table(BusObjectConfig config)
    {
        super(config);
    }

}
