/*
  This class has been generated by the Code Generator
*/

package com.chubb.pfp.pfpwsappserverpackage;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;


public class PFP_ReviewActionSummary extends PFP_ReviewActionSummaryBase
{
    public PFP_ReviewActionSummary()
    {
        this((BusObjectConfig)null);
    }

    public PFP_ReviewActionSummary(BusObjectConfig config)
    {
        super(config);
    }

}
