/*
  This class has been generated by the Code Generator
*/

package com.chubb.pfp.pfpwsappserverpackage;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;
import com.cordys.cpc.bsf.classinfo.AttributeInfo;
import com.cordys.cpc.bsf.classinfo.ClassInfo;
import com.cordys.cpc.bsf.listeners.constraint.NumberValidator;
import com.cordys.cpc.bsf.listeners.constraint.StringValidator;


public abstract class PFP_FollowUpDetailsBase extends com.cordys.cpc.bsf.busobject.StateBusObject
{
    // tags used in the XML document
    public final static String ATTR_SNO = "SNO";
    public final static String ATTR_CaseID = "CaseID";
    public final static String ATTR_CaseTitle = "CaseTitle";
    public final static String ATTR_TaskType = "TaskType";
    public final static String ATTR_TaskInstanceID = "TaskInstanceID";
    public final static String ATTR_Assignee = "Assignee";
    public final static String ATTR_FollowUpDate = "FollowUpDate";
    public final static String ATTR_FollowUpType = "FollowUpType";
    public final static String ATTR_Status = "Status";
    public final static String ATTR_PolicyNumber = "PolicyNumber";
    public final static String ATTR_TargetWorklist = "TargetWorklist";
    public final static String ATTR_CreatedBy = "CreatedBy";
    public final static String ATTR_UpdatedBy = "UpdatedBy";
    public final static String ATTR_CreatedOn = "CreatedOn";
    public final static String ATTR_UpdateOn = "UpdateOn";
    private static ClassInfo s_classInfo = null;
    public static ClassInfo _getClassInfo()//NOPMD framework ensures this is thread safe
    {
        if ( s_classInfo == null )//NOPMD
        {
            s_classInfo = newClassInfo(PFP_FollowUpDetails.class);
            s_classInfo.setTableName("PFP_FollowUpDetails");
            s_classInfo.setUIDElements(new String[]{ATTR_SNO});
            {
                AttributeInfo ai = new AttributeInfo(ATTR_SNO);
                ai.setJavaName(ATTR_SNO);
                ai.setColumnName(ATTR_SNO);
                ai.setAttributeClass(int.class);
                NumberValidator v = new NumberValidator(ATTR_SNO);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CaseID);
                ai.setJavaName(ATTR_CaseID);
                ai.setColumnName(ATTR_CaseID);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_CaseID);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CaseTitle);
                ai.setJavaName(ATTR_CaseTitle);
                ai.setColumnName(ATTR_CaseTitle);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_CaseTitle);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_TaskType);
                ai.setJavaName(ATTR_TaskType);
                ai.setColumnName(ATTR_TaskType);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_TaskType);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_TaskInstanceID);
                ai.setJavaName(ATTR_TaskInstanceID);
                ai.setColumnName(ATTR_TaskInstanceID);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_TaskInstanceID);
                v.setMaxLength(100);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Assignee);
                ai.setJavaName(ATTR_Assignee);
                ai.setColumnName(ATTR_Assignee);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_Assignee);
                v.setMaxLength(100);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_FollowUpDate);
                ai.setJavaName(ATTR_FollowUpDate);
                ai.setColumnName(ATTR_FollowUpDate);
                ai.setAttributeClass(java.sql.Date.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_FollowUpType);
                ai.setJavaName(ATTR_FollowUpType);
                ai.setColumnName(ATTR_FollowUpType);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_FollowUpType);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Status);
                ai.setJavaName(ATTR_Status);
                ai.setColumnName(ATTR_Status);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_Status);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_PolicyNumber);
                ai.setJavaName(ATTR_PolicyNumber);
                ai.setColumnName(ATTR_PolicyNumber);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_PolicyNumber);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_TargetWorklist);
                ai.setJavaName(ATTR_TargetWorklist);
                ai.setColumnName(ATTR_TargetWorklist);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_TargetWorklist);
                v.setMaxLength(500);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CreatedBy);
                ai.setJavaName(ATTR_CreatedBy);
                ai.setColumnName(ATTR_CreatedBy);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_CreatedBy);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_UpdatedBy);
                ai.setJavaName(ATTR_UpdatedBy);
                ai.setColumnName(ATTR_UpdatedBy);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_UpdatedBy);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CreatedOn);
                ai.setJavaName(ATTR_CreatedOn);
                ai.setColumnName(ATTR_CreatedOn);
                ai.setAttributeClass(java.sql.Date.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_UpdateOn);
                ai.setJavaName(ATTR_UpdateOn);
                ai.setColumnName(ATTR_UpdateOn);
                ai.setAttributeClass(java.sql.Date.class);
                s_classInfo.addAttributeInfo(ai);
            }
        }
        return s_classInfo;
    }

    public PFP_FollowUpDetailsBase(BusObjectConfig config)
    {
        super(config);
    }

    public int getSNO()
    {
        return getIntProperty(ATTR_SNO);
    }

    public void setSNO(int value)
    {
        setProperty(ATTR_SNO, value, 0);
    }

    public String getCaseID()
    {
        return getStringProperty(ATTR_CaseID);
    }

    public void setCaseID(String value)
    {
        setProperty(ATTR_CaseID, value, 0);
    }

    public String getCaseTitle()
    {
        return getStringProperty(ATTR_CaseTitle);
    }

    public void setCaseTitle(String value)
    {
        setProperty(ATTR_CaseTitle, value, 0);
    }

    public String getTaskType()
    {
        return getStringProperty(ATTR_TaskType);
    }

    public void setTaskType(String value)
    {
        setProperty(ATTR_TaskType, value, 0);
    }

    public String getTaskInstanceID()
    {
        return getStringProperty(ATTR_TaskInstanceID);
    }

    public void setTaskInstanceID(String value)
    {
        setProperty(ATTR_TaskInstanceID, value, 0);
    }

    public String getAssignee()
    {
        return getStringProperty(ATTR_Assignee);
    }

    public void setAssignee(String value)
    {
        setProperty(ATTR_Assignee, value, 0);
    }

    public java.sql.Date getFollowUpDate()
    {
        return getSqlDateProperty(ATTR_FollowUpDate);
    }

    public void setFollowUpDate(java.sql.Date value)
    {
        setProperty(ATTR_FollowUpDate, value, 0);
    }

    public String getFollowUpType()
    {
        return getStringProperty(ATTR_FollowUpType);
    }

    public void setFollowUpType(String value)
    {
        setProperty(ATTR_FollowUpType, value, 0);
    }

    public String getStatus()
    {
        return getStringProperty(ATTR_Status);
    }

    public void setStatus(String value)
    {
        setProperty(ATTR_Status, value, 0);
    }

    public String getPolicyNumber()
    {
        return getStringProperty(ATTR_PolicyNumber);
    }

    public void setPolicyNumber(String value)
    {
        setProperty(ATTR_PolicyNumber, value, 0);
    }

    public String getTargetWorklist()
    {
        return getStringProperty(ATTR_TargetWorklist);
    }

    public void setTargetWorklist(String value)
    {
        setProperty(ATTR_TargetWorklist, value, 0);
    }

    public String getCreatedBy()
    {
        return getStringProperty(ATTR_CreatedBy);
    }

    public void setCreatedBy(String value)
    {
        setProperty(ATTR_CreatedBy, value, 0);
    }

    public String getUpdatedBy()
    {
        return getStringProperty(ATTR_UpdatedBy);
    }

    public void setUpdatedBy(String value)
    {
        setProperty(ATTR_UpdatedBy, value, 0);
    }

    public java.sql.Date getCreatedOn()
    {
        return getSqlDateProperty(ATTR_CreatedOn);
    }

    public void setCreatedOn(java.sql.Date value)
    {
        setProperty(ATTR_CreatedOn, value, 0);
    }

    public java.sql.Date getUpdateOn()
    {
        return getSqlDateProperty(ATTR_UpdateOn);
    }

    public void setUpdateOn(java.sql.Date value)
    {
        setProperty(ATTR_UpdateOn, value, 0);
    }


    public static BusObjectIterator<com.chubb.pfp.pfpwsappserverpackage.PFP_FollowUpDetails> GetPendingTasksByStatusAndType(String Type, String Status)
    {
        String queryText = "select * from \"PFP_FollowUpDetails\" where \"FollowUpType\" = :Type and \"Status\" = :Status";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("Type", "PFP_FollowUpDetails.FollowUpType", QueryObject.PARAM_STRING, Type);//NOPMD
        query.addParameter("Status", "PFP_FollowUpDetails.Status", QueryObject.PARAM_STRING, Status);//NOPMD
        query.setResultClass(PFP_FollowUpDetails.class);
        return query.getObjects();
    }

    public static com.chubb.pfp.pfpwsappserverpackage.PFP_FollowUpDetails getFollowUpDetailsByCaseID(String CaseID, String Status)
    {
        String queryText = "select * from \"PFP_FollowUpDetails\" where \"CaseID\" = :CaseID and \"Status\" = :Status";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("CaseID", "PFP_FollowUpDetails.CaseID", QueryObject.PARAM_STRING, CaseID);//NOPMD
        query.addParameter("Status", "PFP_FollowUpDetails.Status", QueryObject.PARAM_STRING, Status);//NOPMD
        query.setResultClass(PFP_FollowUpDetails.class);
        return (PFP_FollowUpDetails)query.getObject();
    }

    public static BusObjectIterator<com.chubb.pfp.pfpwsappserverpackage.PFP_FollowUpDetails> getNextPFP_FollowUpDetailsObjects(int SNO, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"PFP_FollowUpDetails\" where (\"SNO\" > :SNO) order by \"SNO\" asc";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("SNO", "PFP_FollowUpDetails.SNO", QueryObject.PARAM_INT, new Integer(SNO));//NOPMD
        query.setResultClass(PFP_FollowUpDetails.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static BusObjectIterator<com.chubb.pfp.pfpwsappserverpackage.PFP_FollowUpDetails> getPFPFollowUpDetailsByStatus(String Status)
    {
        String queryText = "select * from \"PFP_FollowUpDetails\" where \"Status\" = :Status";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("Status", "PFP_FollowUpDetails.Status", QueryObject.PARAM_STRING, Status);//NOPMD
        query.setResultClass(PFP_FollowUpDetails.class);
        return query.getObjects();
    }

    public static com.chubb.pfp.pfpwsappserverpackage.PFP_FollowUpDetails getPFP_FollowUpDetailsObject(int SNO)
    {
        String queryText = "select * from \"PFP_FollowUpDetails\" where \"SNO\" = :SNO";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("SNO", "PFP_FollowUpDetails.SNO", QueryObject.PARAM_INT, new Integer(SNO));//NOPMD
        query.setResultClass(PFP_FollowUpDetails.class);
        return (PFP_FollowUpDetails)query.getObject();
    }

    public static BusObjectIterator<com.chubb.pfp.pfpwsappserverpackage.PFP_FollowUpDetails> getPFP_FollowUpDetailsObjects(int fromSNO, int toSNO, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"PFP_FollowUpDetails\" where \"SNO\" between :fromSNO and :toSNO";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("fromSNO", "PFP_FollowUpDetails.SNO", QueryObject.PARAM_INT, new Integer(fromSNO));
        query.addParameter("toSNO", "PFP_FollowUpDetails.SNO", QueryObject.PARAM_INT, new Integer(toSNO));
        query.setResultClass(PFP_FollowUpDetails.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static BusObjectIterator<com.chubb.pfp.pfpwsappserverpackage.PFP_FollowUpDetails> getPFP_FollowUpDetailsObjects(int fromSNO, int toSNO)
    {
        String queryText = "select * from \"PFP_FollowUpDetails\" where \"SNO\" between :fromSNO and :toSNO";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("fromSNO", "PFP_FollowUpDetails.SNO", QueryObject.PARAM_INT, new Integer(fromSNO));
        query.addParameter("toSNO", "PFP_FollowUpDetails.SNO", QueryObject.PARAM_INT, new Integer(toSNO));
        query.setResultClass(PFP_FollowUpDetails.class);
        return query.getObjects();
    }


    public static BusObjectIterator<com.chubb.pfp.pfpwsappserverpackage.PFP_FollowUpDetails> getPreviousPFP_FollowUpDetailsObjects(int SNO, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"PFP_FollowUpDetails\" where (\"SNO\" < :SNO) order by \"SNO\" desc";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("SNO", "PFP_FollowUpDetails.SNO", QueryObject.PARAM_INT, new Integer(SNO));//NOPMD
        query.setResultClass(PFP_FollowUpDetails.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

}
