/*
  This class has been generated by the Code Generator
*/

package com.chubb.pfp.pfpwsappserverpackage;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;
import com.cordys.cpc.bsf.classinfo.AttributeInfo;
import com.cordys.cpc.bsf.classinfo.ClassInfo;
import com.cordys.cpc.bsf.listeners.constraint.NumberValidator;
import com.cordys.cpc.bsf.listeners.constraint.StringValidator;


public abstract class PFP_UserDetailsBase extends com.cordys.cpc.bsf.busobject.StateBusObject
{
    // tags used in the XML document
    public final static String ATTR_SLNO = "SLNO";
    public final static String ATTR_USRdn = "USRdn";
    public final static String ATTR_USROrganisation = "USROrganisation";
    public final static String ATTR_USREntity = "USREntity";
    public final static String ATTR_USRIdentification = "USRIdentification";
    public final static String ATTR_USRPosition = "USRPosition";
    public final static String ATTR_USRInternalGroup = "USRInternalGroup";
    public final static String ATTR_CreatedBy = "CreatedBy";
    public final static String ATTR_UpdatedBy = "UpdatedBy";
    public final static String ATTR_CreatedOn = "CreatedOn";
    public final static String ATTR_UpdatedOn = "UpdatedOn";
    public final static String ATTR_TermDate = "TermDate";
    public final static String ATTR_USRManager = "USRManager";
    public final static String ATTR_USRCUrrentAvailability = "USRCUrrentAvailability";
    public final static String ATTR_LanID = "LanID";
    public final static String ATTR_UpdatedDate = "UpdatedDate";
    private static ClassInfo s_classInfo = null;
    public static ClassInfo _getClassInfo()//NOPMD framework ensures this is thread safe
    {
        if ( s_classInfo == null )//NOPMD
        {
            s_classInfo = newClassInfo(PFP_UserDetails.class);
            s_classInfo.setTableName("PFP_UserDetails");
            s_classInfo.setUIDElements(new String[]{ATTR_SLNO});
            {
                AttributeInfo ai = new AttributeInfo(ATTR_SLNO);
                ai.setJavaName(ATTR_SLNO);
                ai.setColumnName(ATTR_SLNO);
                ai.setAttributeClass(int.class);
                NumberValidator v = new NumberValidator(ATTR_SLNO);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_USRdn);
                ai.setJavaName(ATTR_USRdn);
                ai.setColumnName(ATTR_USRdn);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_USRdn);
                v.setMaxLength(1000);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_USROrganisation);
                ai.setJavaName(ATTR_USROrganisation);
                ai.setColumnName(ATTR_USROrganisation);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_USROrganisation);
                v.setMaxLength(1000);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_USREntity);
                ai.setJavaName(ATTR_USREntity);
                ai.setColumnName(ATTR_USREntity);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_USREntity);
                v.setMaxLength(1000);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_USRIdentification);
                ai.setJavaName(ATTR_USRIdentification);
                ai.setColumnName(ATTR_USRIdentification);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_USRIdentification);
                v.setMaxLength(2000);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_USRPosition);
                ai.setJavaName(ATTR_USRPosition);
                ai.setColumnName(ATTR_USRPosition);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_USRPosition);
                v.setMaxLength(100);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_USRInternalGroup);
                ai.setJavaName(ATTR_USRInternalGroup);
                ai.setColumnName(ATTR_USRInternalGroup);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_USRInternalGroup);
                v.setMaxLength(3000);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CreatedBy);
                ai.setJavaName(ATTR_CreatedBy);
                ai.setColumnName(ATTR_CreatedBy);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_CreatedBy);
                v.setMaxLength(300);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_UpdatedBy);
                ai.setJavaName(ATTR_UpdatedBy);
                ai.setColumnName(ATTR_UpdatedBy);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_UpdatedBy);
                v.setMaxLength(300);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CreatedOn);
                ai.setJavaName(ATTR_CreatedOn);
                ai.setColumnName(ATTR_CreatedOn);
                ai.setAttributeClass(java.util.Date.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_UpdatedOn);
                ai.setJavaName(ATTR_UpdatedOn);
                ai.setColumnName(ATTR_UpdatedOn);
                ai.setAttributeClass(java.util.Date.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_TermDate);
                ai.setJavaName(ATTR_TermDate);
                ai.setColumnName(ATTR_TermDate);
                ai.setAttributeClass(java.util.Date.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_USRManager);
                ai.setJavaName(ATTR_USRManager);
                ai.setColumnName(ATTR_USRManager);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_USRManager);
                v.setMaxLength(1000);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_USRCUrrentAvailability);
                ai.setJavaName(ATTR_USRCUrrentAvailability);
                ai.setColumnName(ATTR_USRCUrrentAvailability);
                ai.setAttributeClass(double.class);
                NumberValidator v = new NumberValidator(ATTR_USRCUrrentAvailability);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_LanID);
                ai.setJavaName(ATTR_LanID);
                ai.setColumnName(ATTR_LanID);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_LanID);
                v.setMaxLength(500);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_UpdatedDate);
                ai.setJavaName(ATTR_UpdatedDate);
                ai.setColumnName(ATTR_UpdatedDate);
                ai.setAttributeClass(java.sql.Date.class);
                s_classInfo.addAttributeInfo(ai);
            }
        }
        return s_classInfo;
    }

    public PFP_UserDetailsBase(BusObjectConfig config)
    {
        super(config);
    }

    public int getSLNO()
    {
        return getIntProperty(ATTR_SLNO);
    }

    public void setSLNO(int value)
    {
        setProperty(ATTR_SLNO, value, 0);
    }

    public String getUSRdn()
    {
        return getStringProperty(ATTR_USRdn);
    }

    public void setUSRdn(String value)
    {
        setProperty(ATTR_USRdn, value, 0);
    }

    public String getUSROrganisation()
    {
        return getStringProperty(ATTR_USROrganisation);
    }

    public void setUSROrganisation(String value)
    {
        setProperty(ATTR_USROrganisation, value, 0);
    }

    public String getUSREntity()
    {
        return getStringProperty(ATTR_USREntity);
    }

    public void setUSREntity(String value)
    {
        setProperty(ATTR_USREntity, value, 0);
    }

    public String getUSRIdentification()
    {
        return getStringProperty(ATTR_USRIdentification);
    }

    public void setUSRIdentification(String value)
    {
        setProperty(ATTR_USRIdentification, value, 0);
    }

    public String getUSRPosition()
    {
        return getStringProperty(ATTR_USRPosition);
    }

    public void setUSRPosition(String value)
    {
        setProperty(ATTR_USRPosition, value, 0);
    }

    public String getUSRInternalGroup()
    {
        return getStringProperty(ATTR_USRInternalGroup);
    }

    public void setUSRInternalGroup(String value)
    {
        setProperty(ATTR_USRInternalGroup, value, 0);
    }

    public String getCreatedBy()
    {
        return getStringProperty(ATTR_CreatedBy);
    }

    public void setCreatedBy(String value)
    {
        setProperty(ATTR_CreatedBy, value, 0);
    }

    public String getUpdatedBy()
    {
        return getStringProperty(ATTR_UpdatedBy);
    }

    public void setUpdatedBy(String value)
    {
        setProperty(ATTR_UpdatedBy, value, 0);
    }

    public java.util.Date getCreatedOn()
    {
        return getDateTimestampProperty(ATTR_CreatedOn);
    }

    public void setCreatedOn(java.util.Date value)
    {
        setProperty(ATTR_CreatedOn, value, 0);
    }

    public java.util.Date getUpdatedOn()
    {
        return getDateTimestampProperty(ATTR_UpdatedOn);
    }

    public void setUpdatedOn(java.util.Date value)
    {
        setProperty(ATTR_UpdatedOn, value, 0);
    }

    public java.util.Date getTermDate()
    {
        return getDateTimestampProperty(ATTR_TermDate);
    }

    public void setTermDate(java.util.Date value)
    {
        setProperty(ATTR_TermDate, value, 0);
    }

    public String getUSRManager()
    {
        return getStringProperty(ATTR_USRManager);
    }

    public void setUSRManager(String value)
    {
        setProperty(ATTR_USRManager, value, 0);
    }

    public double getUSRCUrrentAvailability()
    {
        return getDoubleProperty(ATTR_USRCUrrentAvailability);
    }

    public void setUSRCUrrentAvailability(double value)
    {
        setProperty(ATTR_USRCUrrentAvailability, value, 0);
    }

    public String getLanID()
    {
        return getStringProperty(ATTR_LanID);
    }

    public void setLanID(String value)
    {
        setProperty(ATTR_LanID, value, 0);
    }

    public java.sql.Date getUpdatedDate()
    {
        return getSqlDateProperty(ATTR_UpdatedDate);
    }

    public void setUpdatedDate(java.sql.Date value)
    {
        setProperty(ATTR_UpdatedDate, value, 0);
    }



    public static BusObjectIterator<com.chubb.pfp.pfpwsappserverpackage.PFP_UserDetails> getNextPFP_UserDetailsObjects(int SLNO, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"PFP_UserDetails\" where (\"SLNO\" > :SLNO) order by \"SLNO\" asc";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("SLNO", "PFP_UserDetails.SLNO", QueryObject.PARAM_INT, new Integer(SLNO));//NOPMD
        query.setResultClass(PFP_UserDetails.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static com.chubb.pfp.pfpwsappserverpackage.PFP_UserDetails getPFP_UserDetailsObject(int SLNO)
    {
        String queryText = "select * from \"PFP_UserDetails\" where \"SLNO\" = :SLNO";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("SLNO", "PFP_UserDetails.SLNO", QueryObject.PARAM_INT, new Integer(SLNO));//NOPMD
        query.setResultClass(PFP_UserDetails.class);
        return (PFP_UserDetails)query.getObject();
    }

    public static BusObjectIterator<com.chubb.pfp.pfpwsappserverpackage.PFP_UserDetails> getPFP_UserDetailsObjects(int fromSLNO, int toSLNO, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"PFP_UserDetails\" where \"SLNO\" between :fromSLNO and :toSLNO";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("fromSLNO", "PFP_UserDetails.SLNO", QueryObject.PARAM_INT, new Integer(fromSLNO));
        query.addParameter("toSLNO", "PFP_UserDetails.SLNO", QueryObject.PARAM_INT, new Integer(toSLNO));
        query.setResultClass(PFP_UserDetails.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static BusObjectIterator<com.chubb.pfp.pfpwsappserverpackage.PFP_UserDetails> getPFP_UserDetailsObjects(int fromSLNO, int toSLNO)
    {
        String queryText = "select * from \"PFP_UserDetails\" where \"SLNO\" between :fromSLNO and :toSLNO";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("fromSLNO", "PFP_UserDetails.SLNO", QueryObject.PARAM_INT, new Integer(fromSLNO));
        query.addParameter("toSLNO", "PFP_UserDetails.SLNO", QueryObject.PARAM_INT, new Integer(toSLNO));
        query.setResultClass(PFP_UserDetails.class);
        return query.getObjects();
    }

    public static BusObjectIterator<com.chubb.pfp.pfpwsappserverpackage.PFP_UserDetails> getPreviousPFP_UserDetailsObjects(int SLNO, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"PFP_UserDetails\" where (\"SLNO\" < :SLNO) order by \"SLNO\" desc";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("SLNO", "PFP_UserDetails.SLNO", QueryObject.PARAM_INT, new Integer(SLNO));//NOPMD
        query.setResultClass(PFP_UserDetails.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

}
