/*
  This class has been generated by the Code Generator
*/

package com.chubb.pfp.pfpwsappserverpackage;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;


public class PFP_TaskDetails extends PFP_TaskDetailsBase
{
    public PFP_TaskDetails()
    {
        this((BusObjectConfig)null);
    }

    public PFP_TaskDetails(BusObjectConfig config)
    {
        super(config);
    }

public static BusObjectIterator<com.chubb.pfp.pfpwsappserverpackage.PFP_TaskDetails> getPFPTaskDetailsWithStatusNull()
    {
        String queryText = "Select * from PFP_TaskDetails Where TaskInstanceID IS NULL";
        QueryObject query = new QueryObject(queryText);        
        query.setResultClass(PFP_TaskDetails.class);       
        return query.getObjects();
    }
	 public static BusObjectIterator<com.chubb.pfp.pfpwsappserverpackage.PFP_TaskDetails> getPFP_TaskDetailsByCaseID(String CaseID)
    {
        String queryText = "Select * from PFP_TaskDetails Where CaseID = :CaseID";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("CaseID", "PFP_TaskDetails.CaseID", QueryObject.PARAM_STRING, CaseID);        
        query.setResultClass(PFP_TaskDetails.class);       
        return query.getObjects();
    }

}
