/*
  This class has been generated by the Code Generator
*/

package com.chubb.pfp.pfpwsappserverpackage;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;


public class PFP_Timer extends PFP_TimerBase
{
    public PFP_Timer()
    {
        this((BusObjectConfig)null);
    }

    public PFP_Timer(BusObjectConfig config)
    {
        super(config);
    }

}
