/*
  This class has been generated by the Code Generator
*/

package com.chubb.pfp.pfpwsappserverpackage;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;


public class PFP_SLAMasterDetails extends PFP_SLAMasterDetailsBase
{
    public PFP_SLAMasterDetails()
    {
        this((BusObjectConfig)null);
    }

    public PFP_SLAMasterDetails(BusObjectConfig config)
    {
        super(config);
    }

public static BusObjectIterator<com.chubb.pfp.pfpwsappserverpackage.PFP_SLAMasterDetails> getSLADetailsByCaseTitleAndStatus(String status, String caseTitle)
    {
		
		String queryText = "";
		
		if("".equalsIgnoreCase(caseTitle) ||  caseTitle == null)
		{
			queryText = "select * from PFP_SLAMasterDetails where Status = '"+status+"'";
		}
		else
		{
			queryText = "select * from PFP_SLAMasterDetails where Status = '"+status+"' and CaseTitle Like '%"+caseTitle+"%' ";		
		}	
		
        
        QueryObject query = new QueryObject(queryText);
		
		if("".equalsIgnoreCase(caseTitle) || caseTitle == null)
		{			
			query.addParameter("toSNO", "PFP_SLAMasterDetails.Status", QueryObject.PARAM_STRING, status);
		}
		else
		{
			query.addParameter("fromSNO", "PFP_SLAMasterDetails.Status", QueryObject.PARAM_STRING, status);
			query.addParameter("toSNO", "PFP_SLAMasterDetails.CaseTitle", QueryObject.PARAM_STRING, caseTitle);
		}
        
        query.setResultClass(PFP_SLAMasterDetails.class);
        return query.getObjects();
    }

}
