/*
  This class has been generated by the Code Generator
*/

package com.chubb.pfp.pfpwsappserverpackage;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;
import com.cordys.cpc.bsf.classinfo.AttributeInfo;
import com.cordys.cpc.bsf.classinfo.ClassInfo;
import com.cordys.cpc.bsf.listeners.constraint.NumberValidator;
import com.cordys.cpc.bsf.listeners.constraint.StringValidator;


public abstract class PFP_RolesBase extends com.cordys.cpc.bsf.busobject.StateBusObject
{
    // tags used in the XML document
    public final static String ATTR_SLNO = "SLNO";
    public final static String ATTR_Organisation = "Organisation";
    public final static String ATTR_Entity = "Entity";
    public final static String ATTR_Role = "Role";
    public final static String ATTR_ADGroup = "ADGroup";
    private static ClassInfo s_classInfo = null;
    public static ClassInfo _getClassInfo()//NOPMD framework ensures this is thread safe
    {
        if ( s_classInfo == null )//NOPMD
        {
            s_classInfo = newClassInfo(PFP_Roles.class);
            s_classInfo.setTableName("PFP_Roles");
            s_classInfo.setUIDElements(new String[]{ATTR_SLNO});
            {
                AttributeInfo ai = new AttributeInfo(ATTR_SLNO);
                ai.setJavaName(ATTR_SLNO);
                ai.setColumnName(ATTR_SLNO);
                ai.setAttributeClass(int.class);
                NumberValidator v = new NumberValidator(ATTR_SLNO);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Organisation);
                ai.setJavaName(ATTR_Organisation);
                ai.setColumnName(ATTR_Organisation);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_Organisation);
                v.setMaxLength(1000);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Entity);
                ai.setJavaName(ATTR_Entity);
                ai.setColumnName(ATTR_Entity);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_Entity);
                v.setMaxLength(1000);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Role);
                ai.setJavaName(ATTR_Role);
                ai.setColumnName(ATTR_Role);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_Role);
                v.setMaxLength(500);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_ADGroup);
                ai.setJavaName(ATTR_ADGroup);
                ai.setColumnName(ATTR_ADGroup);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_ADGroup);
                v.setMaxLength(1000);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
        }
        return s_classInfo;
    }

    public PFP_RolesBase(BusObjectConfig config)
    {
        super(config);
    }

    public int getSLNO()
    {
        return getIntProperty(ATTR_SLNO);
    }

    public void setSLNO(int value)
    {
        setProperty(ATTR_SLNO, value, 0);
    }

    public String getOrganisation()
    {
        return getStringProperty(ATTR_Organisation);
    }

    public void setOrganisation(String value)
    {
        setProperty(ATTR_Organisation, value, 0);
    }

    public String getEntity()
    {
        return getStringProperty(ATTR_Entity);
    }

    public void setEntity(String value)
    {
        setProperty(ATTR_Entity, value, 0);
    }

    public String getRole()
    {
        return getStringProperty(ATTR_Role);
    }

    public void setRole(String value)
    {
        setProperty(ATTR_Role, value, 0);
    }

    public String getADGroup()
    {
        return getStringProperty(ATTR_ADGroup);
    }

    public void setADGroup(String value)
    {
        setProperty(ATTR_ADGroup, value, 0);
    }


    public static BusObjectIterator<com.chubb.pfp.pfpwsappserverpackage.PFP_Roles> getNextPFP_RolesObjects(int SLNO, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"PFP_Roles\" where (\"SLNO\" > :SLNO) order by \"SLNO\" asc";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("SLNO", "PFP_Roles.SLNO", QueryObject.PARAM_INT, new Integer(SLNO));//NOPMD
        query.setResultClass(PFP_Roles.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static com.chubb.pfp.pfpwsappserverpackage.PFP_Roles getPFP_RolesObject(int SLNO)
    {
        String queryText = "select * from \"PFP_Roles\" where \"SLNO\" = :SLNO";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("SLNO", "PFP_Roles.SLNO", QueryObject.PARAM_INT, new Integer(SLNO));//NOPMD
        query.setResultClass(PFP_Roles.class);
        return (PFP_Roles)query.getObject();
    }

    public static BusObjectIterator<com.chubb.pfp.pfpwsappserverpackage.PFP_Roles> getPFP_RolesObjects(int fromSLNO, int toSLNO, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"PFP_Roles\" where \"SLNO\" between :fromSLNO and :toSLNO";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("fromSLNO", "PFP_Roles.SLNO", QueryObject.PARAM_INT, new Integer(fromSLNO));
        query.addParameter("toSLNO", "PFP_Roles.SLNO", QueryObject.PARAM_INT, new Integer(toSLNO));
        query.setResultClass(PFP_Roles.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static BusObjectIterator<com.chubb.pfp.pfpwsappserverpackage.PFP_Roles> getPFP_RolesObjects(int fromSLNO, int toSLNO)
    {
        String queryText = "select * from \"PFP_Roles\" where \"SLNO\" between :fromSLNO and :toSLNO";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("fromSLNO", "PFP_Roles.SLNO", QueryObject.PARAM_INT, new Integer(fromSLNO));
        query.addParameter("toSLNO", "PFP_Roles.SLNO", QueryObject.PARAM_INT, new Integer(toSLNO));
        query.setResultClass(PFP_Roles.class);
        return query.getObjects();
    }

    public static BusObjectIterator<com.chubb.pfp.pfpwsappserverpackage.PFP_Roles> getPreviousPFP_RolesObjects(int SLNO, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"PFP_Roles\" where (\"SLNO\" < :SLNO) order by \"SLNO\" desc";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("SLNO", "PFP_Roles.SLNO", QueryObject.PARAM_INT, new Integer(SLNO));//NOPMD
        query.setResultClass(PFP_Roles.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

}
