/*
  This class has been generated by the Code Generator
*/

package com.chubb.pfp.pfpwsappserverpackage;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObject;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import java.text.SimpleDateFormat; 
import java.util.Date;
import java.text.ParseException;

public class PFP_Util extends PFP_UtilBase
{
    static SimpleDateFormat etDf = new SimpleDateFormat("MM/dd/yyyy' 'hh:mm:ssa");

    public PFP_Util()
    {
        this((BusObjectConfig)null);
    }

    public PFP_Util(BusObjectConfig config)
    {
        super(config);
    }

    public static String GetETTimeinMilliSeconds(long MilliSecondsToConvert)
    {
         long currentDateTime=MilliSecondsToConvert;
	 long convertedETTimeinMS=0;
	 String ETdate="";
	
       Date currentDate = new Date(currentDateTime); 
             
     SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy hh:mm:ssa");
	String dateString = etDf.format(currentDate.getTime());
	//	logger.error("check datestring: "+ dateString);								   
											
	 try{
           
	   Date ddate = sdf.parse(dateString);
	//   logger.error("check date: "+ ddate);
	   ETdate=String.valueOf(ddate);

convertedETTimeinMS=ddate.getTime();
	//  logger.error("check etDate: "+ ETdate);

/*Calendar calendar = Calendar.getInstance();
	calendar.setTime(ddate);
	convertedETTimeinMS= calendar.getTimeInMillis();

 // logger.error("check var12333: "+ convertedETTimeinMS); */
	}catch(ParseException e){
									
	   e.printStackTrace();
	 }
	 return ETdate;
    }

    public void onInsert()
    {
    }

    public void onUpdate()
    {
    }

    public void onDelete()
    {
    }

}
