/*
  This class has been generated by the Code Generator
*/

package com.chubb.pfp.pfpwsappserverpackage;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;

public class PFP_NotesDetails extends PFP_NotesDetailsBase
{
    public PFP_NotesDetails()
    {
        this((BusObjectConfig)null);
    }

    public PFP_NotesDetails(BusObjectConfig config)
    {
        super(config);
    }

    public static BusObjectIterator<com.chubb.pfp.pfpwsappserverpackage.PFP_NotesDetails> GetPFP_NotesforCaseID(String CaseID)
    {
        String queryText = "select * from \"PFP_NotesDetails\" where \"CaseID\" = :CaseID order by SNO desc";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("CaseID", "PFP_NotesDetails.CaseID", QueryObject.PARAM_STRING, CaseID);//NOPMD
        query.setResultClass(PFP_NotesDetails.class);
        return query.getObjects();
    }

}
