/*
  This class has been generated by the Code Generator
*/

package com.chubb.pfp.pfpwsappserverpackage;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;
import com.cordys.cpc.bsf.busobject.BSF;
import com.cordys.cpc.bsf.busobject.BusObject;
import com.cordys.cpc.bsf.busobject.exception.BsfException;
import com.cordys.cpc.bsf.soap.SOAPRequestObject;
import com.cordys.cpc.bsf.busobject.QueryObject;
import com.eibus.xml.nom.Document;
import com.eibus.xml.nom.Node;
import com.eibus.xml.nom.XMLException;


public class PFP_ManualTaskDetails extends PFP_ManualTaskDetailsBase
{
    public PFP_ManualTaskDetails()
    {
        this((BusObjectConfig)null);
    }

    public PFP_ManualTaskDetails(BusObjectConfig config)
    {
        super(config);
    }

public static int getPFPManualTaskNotesObject(int SNO)
{
	String queryText = "select *  from PFP_ManualTaskDetails where SNO =:SNO";
	QueryObject query = new QueryObject(queryText);
	query.addParameter("SNO", "PFP_ManualTaskDetails.SNO",QueryObject.PARAM_INT,SNO);
	query.setResultClass(PFP_ManualTaskDetails.class);
	String note = query.getObject().getStringProperty("Notes");
	int resp=0;
	try 
		{
			resp = BSF.getXMLDocument().parseString(note);
		}
	catch (Exception e) 
		{
			e.printStackTrace();
		}
	return resp;
}


}
