/*
  This class has been generated by the Code Generator
*/

package com.chubb.pfp.pfpwsappserverpackage;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;


public class PFP_Roles extends PFP_RolesBase
{
    public PFP_Roles()
    {
        this((BusObjectConfig)null);
    }

    public PFP_Roles(BusObjectConfig config)
    {
        super(config);
    }

    public static BusObjectIterator<com.chubb.pfp.pfpwsappserverpackage.PFP_Roles> getAdGroupdetaisByRole(String Role)
    {
        String queryText = "select * from \"PFP_Roles\" where Role ='"+Role+"'";
        QueryObject query = new QueryObject(queryText);
     query.addParameter("Role", "PFP_UserDetails.Role", QueryObject.PARAM_STRING, Role);
        query.setResultClass(PFP_Roles.class);
      
        return query.getObjects();
    }

}
