/*
  This class has been generated by the Code Generator
*/

package com.chubb.pfp.pfpwsappserverpackage;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;


public class PFP_UserDetails extends PFP_UserDetailsBase
{
    public PFP_UserDetails()
    {
        this((BusObjectConfig)null);
    }

    public PFP_UserDetails(BusObjectConfig config)
    {
        super(config);
    }

    public static BusObjectIterator<com.chubb.pfp.pfpwsappserverpackage.PFP_UserDetails> GetPositionForUserNewPFP(String UserDN, String OrganizationDN)
    {
        String querytext="Select * from PFP_UserDetails where USRdn= :UserDN and USROrganisation= :OrganizationDN";

       QueryObject query = new QueryObject(querytext);
      query.addParameter("UserDN", "PFP_UserDetails.USRdn", QueryObject.PARAM_STRING, UserDN);
     query.addParameter("OrganizationDN", "PFP_UserDetails.USROrganisation", QueryObject.PARAM_STRING, OrganizationDN);
     query.setResultClass(PFP_UserDetails.class);
       return query.getObjects();
    }

    public static BusObjectIterator<com.chubb.pfp.pfpwsappserverpackage.PFP_UserDetails> GetPositionForUserPFP(String UserDN, String OrganizationDN)
    {
        // TODO implement body
        return null;
    }

}
